"""empty message

Revision ID: 311a2c5c0c89
Revises: 
Create Date: 2024-06-08 07:26:01.053184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311a2c5c0c89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_transaction_card_number',  # <-- Berikan nama untuk constraint
            'card',
            ['card_number'],
            ['card_number']
        )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('membership', sa.Enum('Silver', 'Gold', 'Platinum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('membership')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
