"""empty message

Revision ID: 35ddd7d4f282
Revises: 8d0ba4e945f9
Create Date: 2024-05-30 13:47:34.027257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ddd7d4f282'
down_revision = '8d0ba4e945f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode_image', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('barcode_image')

    # ### end Alembic commands ###
